---
version: '3.3'
services:
    transmission:
        container_name: transmission
        mem_limit: 300m
        cpus: 2
        volumes:
            - '${TRANSMISSION_CONFIG_DIR}:/config'
            - '${TORRENT_WATCH_DIR}:/watch'
            - '${DOWNLOADS_DIR}:/downloads'
        environment:
            - TRANSMISSION_WEB_HOME=/combustion-release/
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
            - USER=${WEB_USERNAME}
            - PASS=${WEB_PASSWORD}
        ports:
            - '9091:9091'
            - '51413:51413'
            - '51413:51413/udp'
        image: linuxserver/transmission
        restart: unless-stopped
    jackett:
        container_name: jackett
        mem_limit: 100m
        cpus: 1
        volumes:
            - '${JACKETT_CONFIG_DIR}:/config'
            - '${DOWNLOADS_DIR}:/downloads'
        environment:
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
        ports:
            - '9117:9117'
        image: linuxserver/jackett
        restart: unless-stopped
    radarr:
        container_name: radarr
        depends_on: 
            - "transmission"
            - "jackett"
            - "bazarr"
        mem_limit: 500m
        cpus: 1.5
        volumes:
            - '${RADARR_CONFIG_DIR}:/config'
            - '${DOWNLOADS_DIR}:/downloads'
            - '${MOVIES_DIR}/:/movies'
        environment:
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
        ports:
            - '7878:7878'
        image: linuxserver/radarr
        restart: unless-stopped
    sonarr:
        container_name: sonarr
        depends_on: 
            - "transmission"
            - "jackett"
            - "bazarr"
        mem_limit: 500m
        cpus: 1.5
        volumes:
            - '${SONARR_CONFIG_DIR}:/config'
            - '${SERIES_DIR}:/tv'
            - '${DOWNLOADS_DIR}:/downloads'
        environment:
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
        ports:
            - '8989:8989'
        image: linuxserver/sonarr
        restart: unless-stopped
    bazarr:
        image: linuxserver/bazarr
        mem_limit: 100m
        cpus: 1
        container_name: bazarr
        environment:
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
        volumes:
            - '${BAZARR_CONFIG_DIR}:/config'
            - '${SERIES_DIR}:/tv'
            - '${MOVIES_DIR}:/movies'
        ports:
            - '6767:6767'
        restart: unless-stopped
    jellyfin:
        container_name: jellyfin
        volumes:
            - '${JELLYFIN_CONFIG_DIR}:/config'
            - '${MOVIES_DIR}:/data/movies'
            - '${SERIES_DIR}:/data/tvshows'
        environment: 
            - PUID=${USERID}
            - PGID=${GROUPID}
            - TZ=${TIMEZONE}
        ports:
            - '8096:8096'
        image: linuxserver/jellyfin
        restart: unless-stopped
networks:
  default:
    name: mediacenter_containers
